yaml

name: Continuous Integration

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Sync uv
        run: uv sync
      
      - name: Lint code
        run: uv run ruff check .

      - name: Check formatting
        run: uv run ruff format --check .
